### ISSUE TITLE
 해당 에러 발생 후 강제 종료가 됩니다.

### ISSUE THREAD

**Issue by tnalswjd** [KUR-creative/SickZil-Machine#81]
file:///E:/DOWNLOAD/SickZil-Machine-0.1.1-pre0-win64-gpu-kor/main/PyQt5/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: Failed to initialize QSettings instance. Status code is: 1
file:///E:/DOWNLOAD/SickZil-Machine-0.1.1-pre0-win64-gpu-kor/main/PyQt5/Qt/qml/QtQuick/Dialogs/DefaultFileDialog.qml:102:33: QML Settings: The following application identifiers have not been set: QVector("organizationName", "organizationDomain")
WARNING: Logging before flag parsing goes to stderr.
W0212 00:56:16.498801 22140 deprecation_wrapper.py:119] From src\core.py:172: The name tf.Session is deprecated. Please use tf.compat.v1.Session instead.

Traceback (most recent call last):
  File "src\gui.py", line 163, in rm_txt
  File "src\imgio.py", line 57, in save
  File "site-packages\imageio\core\functions.py", line 259, in imwrite
  File "site-packages\imageio\core\functions.py", line 187, in get_writer
  File "site-packages\imageio\core\format.py", line 178, in get_writer
  File "site-packages\imageio\core\format.py", line 214, in __init__
  File "site-packages\imageio\plugins\pillow.py", line 350, in _open
  File "site-packages\imageio\plugins\pillow.py", line 197, in _open
  File "site-packages\imageio\core\request.py", line 349, in get_file
PermissionError: [Errno 13] Permission denied: 'E:\\DOWNLOAD\\SickZil-Machine-0.1.1-pre0-win64-gpu-kor\\asdfasd\\Yama_No_Susume_v01-05s\\Yama_No_Susume 01-05\\Yama no Susume v01\\Yama no Susume v01_mproj\\images\\009.png'

마스크까지 생성 후 텍스트 지우는 기능을 실행 시키면 해당 메세지 출력 후 프로그램이 강제 종료가 됩니다.

**Comment by phyyou** [comment]
PermissionError면 관리자 권한으로 한번 실행시켜보면 될거 같은데요

**Comment by phyyou** [comment]
@KUR-creative 이슈좀 닫아주세요
