### ISSUE TITLE
Program Crash with Exit code 3221226505

### ISSUE THREAD

**Issue by LPFchan** [KUR-creative/SickZil-Machine#98]
Currently I'm on `0.1.1-pre0-win64-gpu-kor` and program crashes whenever I try to generate masks from image. 

```
Traceback (most recent call last):
  File "site-packages\tensorflow\python\client\session.py", line 1356, in _do_call
  File "site-packages\tensorflow\python\client\session.py", line 1341, in _run_fn
  File "site-packages\tensorflow\python\client\session.py", line 1429, in _call_tf_sessionrun
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,32,1520,2096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node snet/concatenate_4/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,32,1520,2096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[{{node snet/concatenate_4/concat}}]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[snet/conv2d_19/truediv/_5]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\gui.py", line 144, in gen_mask
  File "src\gui.py", line 20, in imgpath2mask
  File "src\utils\fp.py", line 5, in <lambda>
  File "site-packages\funcy\funcs.py", line 106, in <lambda>
  File "site-packages\funcy\funcs.py", line 106, in <lambda>
  File "src\core.py", line 104, in segmap
  File "src\utils\fp.py", line 5, in <lambda>
  File "site-packages\funcy\funcs.py", line 106, in <lambda>
  File "site-packages\funcy\funcs.py", line 106, in <lambda>
  File "site-packages\funcy\funcs.py", line 106, in <lambda>
  [Previous line repeated 1 more time]
  File "src\core.py", line 103, in <lambda>
  File "src\core.py", line 69, in segment
  File "src\core.py", line 59, in segment
  File "src\core.py", line 37, in segment_or_oom
  File "src\core.py", line 97, in snet
  File "site-packages\tensorflow\python\client\session.py", line 950, in run
  File "site-packages\tensorflow\python\client\session.py", line 1173, in _run
  File "site-packages\tensorflow\python\client\session.py", line 1350, in _do_run
  File "site-packages\tensorflow\python\client\session.py", line 1370, in _do_call
tensorflow.python.framework.errors_impl.ResourceExhaustedError: 2 root error(s) found.
  (0) Resource exhausted: OOM when allocating tensor with shape[1,32,1520,2096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node snet/concatenate_4/concat (defined at src\core.py:25) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

  (1) Resource exhausted: OOM when allocating tensor with shape[1,32,1520,2096] and type float on /job:localhost/replica:0/task:0/device:GPU:0 by allocator GPU_0_bfc
         [[node snet/concatenate_4/concat (defined at src\core.py:25) ]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

         [[snet/conv2d_19/truediv/_5]]
Hint: If you want to see a list of allocated tensors when OOM happens, add report_tensor_allocations_upon_oom to RunOptions for current allocation info.

0 successful operations.
0 derived errors ignored.

Original stack trace for 'snet/concatenate_4/concat':
  File "src\main.py", line 11, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\kur\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "src\gui.py", line 12, in <module>
  File "<frozen importlib._bootstrap>", line 971, in _find_and_load
  File "<frozen importlib._bootstrap>", line 955, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 665, in _load_unlocked
  File "c:\users\kur\appdata\local\programs\python\python36\lib\site-packages\PyInstaller\loader\pyimod03_importers.py", line 627, in exec_module
  File "src\core.py", line 27, in <module>
  File "src\core.py", line 25, in load_model
  File "site-packages\tensorflow\python\util\deprecation.py", line 507, in new_func
  File "site-packages\tensorflow\python\framework\importer.py", line 443, in import_graph_def
  File "site-packages\tensorflow\python\framework\importer.py", line 236, in _ProcessNewOps
  File "site-packages\tensorflow\python\framework\ops.py", line 3751, in _add_new_tf_operations
  File "site-packages\tensorflow\python\framework\ops.py", line 3751, in <listcomp>
  File "site-packages\tensorflow\python\framework\ops.py", line 3641, in _create_op_from_tf_operation
  File "site-packages\tensorflow\python\framework\ops.py", line 2005, in __init__

[코드 3221226505로 프로세스 종료됨]
```

**Comment by LPFchan** [comment]
CPU version is free of this bug.
